spring:
  servlet:
    multipart:
      max-file-size: 2000MB  # 设置单个文件最大大小
      max-request-size: 2150MB  # 设置整个请求的最大大小
  datasource:
    url: jdbc:mysql://wxl475.cn:3306/
    username: syf
    password: PrjtmBwCRwsY8bmX
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: wxl475.cn
      port: 6382
      password: wxl5211314
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms
  mail:
    host: smtp.qq.com
    username: 2146765861@qq.com
    password: ybmrbhsvbqwldjgb
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: utf-8
  jackson:
    default-property-inclusion: non_null

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  # 访问的url
  endpoint: http://wxl475.cn
  # API的端口
  port: 9000
  # 秘钥
  accessKey: Gzbw8F6d9xxYjkZwHSGs
  secretKey: JgYhU5NX3Ycw8Yzq9V5smzSwgiK0sCC3iBrPYisp
  secure: false
  bucket-name: syf # 桶名
  image-size: 10485760 # 图片文件的最大大小
  file-size: 1073741824 # 文件的最大大小

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8081

ai:
  appKey: kwuAM5KB9hKft3WJsPyzdlLK
  secretKey: clnu25Q0Zesytom38yl4uXX0rx944vIw

custom:
  okhttp:
    connectTimeout: 300  # 连接超时时间（秒）
    writeTimeout: 300    # 写入超时时间（秒）
    readTimeout: 300     # 读取超时时间（秒）


aliyun:
  accessKeyId: LTAI5tQqugm6r3VwZn8t4iph
  accessKeySecret: d9AFGkmUygC8svruWOuVHNQffsWELS
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucketName: alexoh
  vod:
    regionId: cn-shanghai # 如"cn-shanghai"

